COMMENT

   **************************************************
   File generated by: neuroConstruct v1.7.1 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   Kdr_ChannelML (Type: Channel mechanism, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@units = Physiological Units 
   /channelml/notes = ChannelML file containing a single Channel description 
   /channelml/channel_type/@name = Kdr_ChannelML 
   /channelml/channel_type/@density = yes 
   /channelml/channel_type/status/@value = in_progress 
   /channelml/channel_type/status/comment = Equations adapted from paper for modern convention of external potential being zero 
   /channelml/channel_type/status/contributor/name = Padraig Gleeson 
   /channelml/channel_type/notes = Mitral cell K DR channel 
   /channelml/channel_type/neuronDBref/modelName = K channels 
   /channelml/channel_type/neuronDBref/uri = http://senselab.med.yale.edu/neuronDB/channelGene2.aspx#table3 
   /channelml/channel_type/current_voltage_relation/@cond_law = ohmic 
   /channelml/channel_type/current_voltage_relation/@ion = k 
   /channelml/channel_type/current_voltage_relation/@default_gmax = 1.0 
   /channelml/channel_type/current_voltage_relation/@default_erev = -86.5 
   /channelml/channel_type/current_voltage_relation/@charge = 1 
   /channelml/channel_type/current_voltage_relation/q10_settings/@q10_factor = 3 
   /channelml/channel_type/current_voltage_relation/q10_settings/@experimental_temp = 24 
   /channelml/channel_type/current_voltage_relation/gate/@name = m 
   /channelml/channel_type/current_voltage_relation/gate/@instances = 1 
   /channelml/channel_type/current_voltage_relation/gate/closed_state/@id = m0 
   /channelml/channel_type/current_voltage_relation/gate/open_state/@id = m 
   /channelml/channel_type/current_voltage_relation/gate/open_state/@fraction = 1 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@name = alpha 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@from = m0 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@to = m 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@expr_form = exponential 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@rate = 1 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@scale = 18.1818181818 
   /channelml/channel_type/current_voltage_relation/gate/transition[1]/@midpoint = -50 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@name = beta 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@from = m 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@to = m0 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@expr_form = exponential 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@rate = 1 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@scale = 36.3636363636 
   /channelml/channel_type/current_voltage_relation/gate/transition[2]/@midpoint = -50 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@name = tau 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@from = m0 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@to = m 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@expr_form = generic 
   /channelml/channel_type/current_voltage_relation/gate/time_course/@expr = beta/(0.0035 *( 1 +alpha)) 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@name = inf 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@from = m0 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@to = m 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@expr_form = sigmoid 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@rate = 1 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@scale = -10 
   /channelml/channel_type/current_voltage_relation/gate/steady_state/@midpoint = 21 
   /channelml/channel_type/impl_prefs/table_settings/@max_v = 100 
   /channelml/channel_type/impl_prefs/table_settings/@min_v = -100 
   /channelml/channel_type/impl_prefs/table_settings/@table_divisions = 400 

// File from which this was generated: /home/Simon/Channel_Kinetics/AccessoryOlfactoryBulb/MitralCell/neuroConstruct/AOB_MC_Single_Channel_Tests/cellMechanisms/Kdr_ChannelML/KChannel.xml

// XSL file with mapping to simulator: /home/Simon/Channel_Kinetics/AccessoryOlfactoryBulb/MitralCell/neuroConstruct/AOB_MC_Single_Channel_Tests/cellMechanisms/Kdr_ChannelML/ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file containing a single Channel description
ENDCOMMENT

TITLE Channel: Kdr_ChannelML

COMMENT
    Mitral cell K DR channel
ENDCOMMENT


UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX Kdr_ChannelML
    USEION k READ ek WRITE ik VALENCE 1 ? reversal potential of ion is read, outgoing current is written
           
        
    RANGE gmax, gion
    
    RANGE minf, mtau
    
}

PARAMETER { 
      

    gmax = 0.001 (S/cm2)  ? default value, should be overwritten when conductance placed on cell
    
}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
          

    ? Reversal potential of k
    ek (mV)
    ? The outward flow of ion: k calculated by rate equations...
    ik (mA/cm2)
    
    
    gion (S/cm2)
    minf
    mtau (ms)
    
}

BREAKPOINT { 
                        
    SOLVE states METHOD cnexp
        
    gion = gmax * ((1*m)
^1)      

    ik = gion*(v - ek)
            

}



INITIAL {
    
    ek = -86.5
        
    rates(v)
    m = minf
        
    
}
    
STATE {
    m
    
}



DERIVATIVE states {
    rates(v)
    m' = (minf - m)/mtau
            

}

PROCEDURE rates(v(mV)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta
, temp_adj_m,
         A_alpha_m, B_alpha_m, Vhalf_alpha_m,
         A_beta_m, B_beta_m, Vhalf_beta_m,
         A_inf_m, B_inf_m, Vhalf_inf_m
    
    TABLE minf, mtau
 DEPEND celsius FROM -100 TO 100 WITH 400
    
    UNITSOFF
    
    ? There is a Q10 factor which will alter the tau of the gates 
                 

    temp_adj_m = 3^((celsius - 24)/10)
            
                
           

        
    ?      ***  Adding rate equations for gate: m  ***
        
    ? Found a parameterised form of rate equation for alpha, using expression: A*exp((v-Vhalf)/B)
    A_alpha_m = 1
    B_alpha_m = 18.1818181818
    Vhalf_alpha_m = -50 
    alpha = A_alpha_m * exp((v - Vhalf_alpha_m) / B_alpha_m)
    
    
    ? Found a parameterised form of rate equation for beta, using expression: A*exp((v-Vhalf)/B)
    A_beta_m = 1
    B_beta_m = 36.3636363636
    Vhalf_beta_m = -50 
    beta = A_beta_m * exp((v - Vhalf_beta_m) / B_beta_m)
    
     
    ? Found a generic form of the rate equation for tau, using expression: beta/(0.0035 *( 1 +alpha))
    tau = beta/(0.0035 *( 1 +alpha))
        
    mtau = tau/temp_adj_m
    
    ? Found a parameterised form of rate equation for inf, using expression: A / (1 + exp((v-Vhalf)/B))
    A_inf_m = 1
    B_inf_m = -10
    Vhalf_inf_m = 21 
    inf = A_inf_m / (exp((v - Vhalf_inf_m) / B_inf_m) + 1)
    
    minf = inf
    


    ?     *** Finished rate equations for gate: m ***
    

         

}


UNITSON


